dependencies {
    // JIJ dependencies
    var geckoLibDependency = api(deps.geckoLib.get())
    var smartBrainLibDependency = api(deps.smartBrainLib.get())
    var modularUIDependency = api(deps.modularUI.get())
    if (enableJarJarDependencies) {
        jarJar(geckoLibDependency) {
            version {
                strictly '[4.8, 5.0)'
                prefer deps.versions.geckoLib.get()
            }
        }
        jarJar(smartBrainLibDependency) {
            version {
                strictly '[1.16, 1.17)'
                prefer deps.versions.smartBrainLib.get()
            }
        }
        jarJar(modularUIDependency) {
            version {
                strictly "[${deps.versions.modularUI.get()}]"
                prefer deps.versions.modularUI.get()
            }
        }
    }
    includedLibrary(api(project(':SyncSystem')) { transitive = false })

    // Recipe Viewers
    compileOnly(deps.bundles.jei)
    compileOnly(deps.bundles.rei)
    compileOnly(deps.emi)

    // Curios
    compileOnly(variantOf(deps.curios) { classifier("api") })

    // WAILA-likes
    compileOnly(deps.theOneProbe)
    compileOnly(deps.jade)

    // KJS
    compileOnly(deps.bundles.kjs)

    // Rendering & Optimizations
    compileOnly(deps.sodium)
    compileOnly(deps.iris)
    compileOnly(deps.modernFix)

    // Teams
    compileOnly(deps.ftbLibrary)
    compileOnly(deps.ftbTeams)
    compileOnly(deps.ftbQuests)
    compileOnly(deps.resourcefulLib)
    compileOnly(deps.argonauts)
    compileOnly(deps.heracles)

    // Maps
    compileOnly(deps.ftbChunks)
    compileOnly(deps.xaerosMiniMap)
    compileOnly(deps.xaerosWorldMap)
    compileOnly(deps.journeyMap.api)
    compileOnly(deps.journeyMap.neoforge)

    // Standard runtime mods //
    localRuntime(deps.jade)
    localRuntime(deps.spark)
    localRuntime(deps.modernFix)
    localRuntime(deps.curios)

    // Runtime Recipe Viewers - uncomment whichever one you want to use //
    localRuntime(deps.emi)
//    localRuntime(deps.jei.neoforge.impl)
//    localRuntime(deps.bundles.rei.runtime)

    // Client-only runtime mods //
    clientLocalRuntime(deps.sodium)
    clientLocalRuntime(deps.iris)
    renderNurseCfg(libs.renderNurse)

    //////////////////////////////////////////////////////
    // Runtime mods for dev testing with unclean client //
    //////////////////////////////////////////////////////
    extraLocalRuntime(deps.bundles.kjs)

    extraLocalRuntime(deps.ftbLibrary)
    extraLocalRuntime(deps.ftbTeams)
    extraLocalRuntime(deps.ftbQuests)

//    extraLocalRuntime(deps.heracles)
//    extraLocalRuntime(deps.resourcefulLib)

//    extraLocalRuntime(deps.xaerosminimap)
//    extraLocalRuntime(deps.xaerosworldmap)
//    extraLocalRuntime(deps.journeymap.neoforge)
//    extraLocalRuntime(deps.ftbchunks)

    extraLocalRuntime(deps.kotlinForForge) {
        transitive = false
    }
    extraLocalRuntime(deps.observable)
}
