pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.0.21'
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        deps {
            from(files("gradle/deps.versions.toml"))
        }
    }
}

include("ModularUI")
include("SyncSystem")

rootProject.name = "${mod_id}"
