# Compilation/Dependency bundling flags
enableJarJarDependencies = true

# Mod Info
mod_id = modularui
mod_name = ModularUI
mod_license = LGPL-3.0
mod_version = 3.0.4
mod_description = A GUI library to ease the process of creating vanilla style GUIs. Heavily inspired by GTCE's ModularUI
mod_authors = GregTech Modern team, brachy84, screret
mod_credits = GTCE Author for the idea and concept, Kila Bash for improvements in GTCEu, GregTech Modern team for porting to 1.20.1
mod_url = https://github.com/Argent-Matter/MagicOfTheMind/tree/1.21.1/ModularUI
mod_issue_tracker = https://github.com/Argent-Matter/MagicOfTheMind/issues/
maven_group = dev.screret.modularui
