name: Publish All Subprojects

on:
  workflow_dispatch:
    inputs:
      simulate:
        description: 'Whether to actually publish to the maven'
        required: false
        type: boolean
        default: false
      branch:
        description: 'Branch to checkout (must be 1.21.1 to publish)'
        required: false
        type: string
        default: '1.21.1'

jobs:
  publish:
    name: Build and Publish Subprojects
    strategy:
      matrix:
        project: [ 'ModularUI', 'SyncSystem' ]
    secrets: inherit
    uses: ./.github/workflows/publish-subproject.yml
    with:
      simulate: ${{ inputs.simulate || github.repository_owner != 'Argent-Matter' }}
      branch: ${{ inputs.branch }}
      project: ${{ matrix.project }}
