name: Publish on Release

on:
  release:
    types: [released]

jobs:
  publish-21:
    name: 1.21.1
    secrets: inherit
    uses: ./.github/workflows/publish.yml
    with:
      simulate: ${{ startsWith(github.event.release.name, 'simulate') || github.repository_owner != 'Argent-Matter' }}
      branch: '1.21.1'
      tag-name: ${{ github.ref_name }}
      release-body: ${{ github.event.release.body }}
